const SB="https://cmmnqckszwgsvaaawouw.supabase.co";
const KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbW5xY2tzendnc3ZhYWF3b3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1MDM3OTcsImV4cCI6MjEwMzA3OTc5N30.3q6gLw1Zz2ql__Va29fYPwjCkdnJ9-cO1MmKmluF30g";
const TOP=["Stockholm","Göteborg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Norrköping","Jönköping","Lund","Umeå","Eskilstuna"];
const SITE="https://pizza-meny.vercel.app";
const COLS="id,name,city,country,phone,lat,lon,menu_url,description,rating,is_sponsored";
const LEAK=["København","Kobenhavn","Copenhagen","Oslo","Helsinki","Vaasa"];
let all=[],items=[],filter="all",sort="rank",city="",me=null,ovenP=null,formOpen=0,typeT=0;
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,c=>"&#"+c.charCodeAt(0)+";")}
function emailOk(s){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(s||"").trim())}
function safeHttp(u){u=String(u||"").trim();return /^https?:\/\//i.test(u)&&u.indexOf(" ")<0&&u.indexOf("<")<0?u:""}
function safeTel(p){const d=String(p||"").replace(/[^\d+]/g,"");return d.length>=7?d:""}
function uuidOk(id){return /^[0-9a-f-]{8,36}$/i.test(String(id||""))}
function tooSoon(key,ms){const last=+localStorage.getItem(key)||0;if(Date.now()-last<ms)return true;localStorage.setItem(key,String(Date.now()));return false}
function favs(){try{const a=JSON.parse(localStorage.getItem("pm_fav")||"[]");return Array.isArray(a)?a.filter(uuidOk):[]}catch(e){return[]}}
function saveFav(a){localStorage.setItem("pm_fav",JSON.stringify(a.filter(uuidOk).slice(0,400)))}
function isFav(id){return favs().includes(id)}
function toggleFav(id){if(!uuidOk(id))return;const a=favs();const i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);saveFav(a);render();if(document.getElementById("detailPage").classList.contains("on"))openDetail(id)}
function profile(){try{const p=JSON.parse(localStorage.getItem("pm_me")||"{}");return p&&typeof p==="object"?p:{}}catch(e){return{}}}
function saveProfile(p){localStorage.setItem("pm_me",JSON.stringify({id:String(p.id||"").slice(0,40),name:String(p.name||"").slice(0,80),email:String(p.email||"").slice(0,120),verified:!!p.verified,verify:p.verified?"":String(p.verify||"").slice(0,64)}))}
function newTok(){const a=new Uint8Array(16);if(crypto.getRandomValues)crypto.getRandomValues(a);return Array.from(a,b=>("0"+(b&255).toString(16)).slice(-2)).join("")}
function verifyUrl(){const p=profile();return p.verify?SITE+"/?verify="+encodeURIComponent(p.verify):""}
function applyVerify(){let t="";try{t=new URLSearchParams(location.search).get("verify")||""}catch(e){}if(!t||t.length<16)return;const p=profile();if(p.verify&&p.verify===t&&p.email){p.verified=true;p.verify="";saveProfile(p);try{history.replaceState({},"",location.pathname)}catch(e){}}}
function paintMe(){const p=profile();const vbox=document.getElementById("verifyBox");const fbox=document.getElementById("friendsBox");if(vbox)vbox.style.display=(!p.verified&&p.email&&p.verify)?"block":"none";if(fbox)fbox.style.display=(p.verified&&p.email)?"block":"none";const hint=document.getElementById("mehint");if(!hint)return;hint.textContent=p.verified?"Konto: "+(p.name||p.email)+" · verifierad.":p.email?"Konto skapat. Verifiera e-post innan vänner syns.":"Namn och e-post. E-post krävs."}
function openMe(){const p=profile();document.getElementById("mename").value=p.name||"";document.getElementById("memail").value=p.email||"";paintMe();document.getElementById("meMask").classList.add("on")}
function saveMe(){const name=document.getElementById("mename").value.trim().slice(0,80);const email=document.getElementById("memail").value.trim().toLowerCase().slice(0,120);if(!name){alert("Skriv ditt namn");return}if(!emailOk(email)){alert("E-post krävs för att öppna konto");return}const p=profile();if(p.email!==email){p.verified=false;p.verify=newTok()}if(!p.verify&&!p.verified)p.verify=newTok();p.name=name;p.email=email;if(!p.id)p.id="u"+Date.now();saveProfile(p);paintMe();if(!tooSoon("pm_konto",60000))fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({kind:"konto",name,city:"Konto",phone:null,website:email,note:"verify_pending"})}).catch(()=>{});if(p.verified)document.getElementById("meMask").classList.remove("on");else alert("Konto skapat. Kopiera verifieringslänken och öppna den på den här telefonen.")}
function copyVerify(){const u=verifyUrl();if(!u){alert("Skapa konto först");return}if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(u).then(()=>alert("Länk kopierad. Öppna den här.")).catch(()=>{location.href=u});else location.href=u}
function rates(){try{const r=JSON.parse(localStorage.getItem("pm_rate")||"{}");return r&&typeof r==="object"?r:{}}catch(e){return{}}}
function setRate(id,n){if(!uuidOk(id)||n<1||n>5)return;const r=rates();r[id]=n;localStorage.setItem("pm_rate",JSON.stringify(r));if(document.getElementById("detailPage").classList.contains("on"))openDetail(id)}
function recents(){try{const a=JSON.parse(localStorage.getItem("pm_q")||"[]");return Array.isArray(a)?a.map(x=>String(x).slice(0,40)).slice(0,8):[]}catch(e){return[]}}
function rememberQ(){const v=document.getElementById("q").value.trim().slice(0,40);if(v.length<2)return;const a=recents().filter(x=>x.toLowerCase()!==v.toLowerCase());a.unshift(v);localStorage.setItem("pm_q",JSON.stringify(a.slice(0,8)));drawRecent()}
function drawRecent(){const a=recents();document.getElementById("recent").innerHTML=a.length?a.map(x=>`<button class="chip" onclick='useRecent(${JSON.stringify(String(x))})'>${esc(x)}</button>`).join("")+`<button class="chip" onclick="localStorage.removeItem('pm_q');drawRecent()">Rensa</button>`:""}
function useRecent(v){document.getElementById("q").value=String(v||"").slice(0,40);onType()}
function km(a,b,c,d){const R=6371,p=Math.PI/180,dLat=(c-a)*p,dLon=(d-b)*p;const x=Math.sin(dLat/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function askNear(){if(!navigator.geolocation){alert("Ingen GPS");return}navigator.geolocation.getCurrentPosition(p=>{me={lat:p.coords.latitude,lon:p.coords.longitude};render()},{enableHighAccuracy:true,timeout:8000})}
function okCity(p){const c=(p.city||"");if(LEAK.some(x=>c.toLowerCase()===x.toLowerCase()))return false;if((p.country||"Sverige")!=="Sverige"&&(p.country||"")!=="Sweden")return false;return true}
function clean(rows){const seen=new Set();return rows.filter(p=>p&&p.id&&uuidOk(p.id)&&!seen.has(p.id)&&(seen.add(p.id),okCity(p)))}
function paint(msg){document.getElementById("sub").textContent=msg||(all.length+" pizzerior · live");drawCities();drawRecent();render()}
function readCache(){try{const c=JSON.parse(localStorage.getItem("pm_cache")||"null");if(!c||!Array.isArray(c.rows)||!c.rows.length)return null;return c}catch(e){return null}}
function writeCache(){try{localStorage.setItem("pm_cache",JSON.stringify({t:Date.now(),rows:all}))}catch(e){}}
async function page(off){const r=await fetch(SB+"/rest/v1/pizzerias?select="+COLS+"&order=id.asc&limit=1000&offset="+off,{headers:{apikey:KEY,Authorization:"Bearer "+KEY,Prefer:"count=exact"}});if(!r.ok)throw new Error("Kunde inte läsa listan");return {rows:await r.json(),total:parseInt(((r.headers.get("content-range")||"").split("/")[1]||"0"),10)}}
async function loadItems(){try{const ir=await fetch(SB+"/rest/v1/pizza_items?select=pizzeria_id,name,price_sek",{headers:{apikey:KEY,Authorization:"Bearer "+KEY}});items=ir.ok?await ir.json():[]}catch(e){items=[]}}
async function load(){applyVerify();city=localStorage.getItem("pm_city")||"";if(city)document.getElementById("q").value=city;const cached=readCache();if(cached){all=clean(cached.rows);paint(all.length+" pizzerior")}try{const first=await page(0);all=clean(first.rows);paint(all.length+" pizzerior · live");loadItems();let off=1000,total=first.total||all.length;while(off<total){const p=await page(off);all=clean(all.concat(p.rows));total=p.total||total;off+=1000}writeCache();paint(all.length+" pizzerior · live")}catch(e){if(!all.length){document.getElementById("sub").textContent="Fel";document.getElementById("list").innerHTML="<div class='empty'>Kunde inte läsa listan.</div>"}}}
function drawCities(){document.getElementById("cities").innerHTML=`<button class="city ${!city?"on":""}" onclick="setCity('')">Alla städer</button>`+TOP.map(c=>`<button class="city ${city===c?"on":""}" onclick='setCity(${JSON.stringify(c)})'>${esc(c)}</button>`).join("")}
function setCity(c){city=String(c||"");document.getElementById("q").value=city;localStorage.setItem("pm_city",city);if(city)rememberQ();syncClear();drawCities();render()}
function setF(f){filter=f;document.querySelectorAll("[data-f]").forEach(c=>c.classList.toggle("on",c.dataset.f===f));if(f==="near"&&!me)askNear();render()}
function onType(){syncClear();clearTimeout(typeT);typeT=setTimeout(()=>{const v=document.getElementById("q").value.trim();city=TOP.find(c=>c.toLowerCase()===v.toLowerCase())||"";if(city)localStorage.setItem("pm_city",city);drawCities();render()},80)}
function wipe(){document.getElementById("q").value="";city="";localStorage.removeItem("pm_city");syncClear();drawCities();render();document.getElementById("q").focus()}
function syncClear(){document.getElementById("clr").classList.toggle("on",!!(document.getElementById("q").value||city))}
function menuOf(id){return items.filter(x=>x.pizzeria_id===id)}
function getList(){const q=document.getElementById("q").value.toLowerCase().trim();const cities=new Set(all.map(p=>(p.city||"").toLowerCase()).filter(Boolean));const exactCity=(city||"").toLowerCase()||(cities.has(q)?q:"");let list=all.filter(p=>{if(filter==="fav"&&!isFav(p.id))return false;if(filter==="near")return !!(p.lat&&p.lon&&me);if(exactCity)return (p.city||"").toLowerCase()===exactCity;if(!q)return true;return (p.name+" "+(p.city||"")).toLowerCase().includes(q)});if(filter==="near"&&me)list=list.map(p=>({p,d:km(me.lat,me.lon,p.lat,p.lon)})).filter(x=>x.d<=25).sort((a,b)=>a.d-b.d).map(x=>x.p);else list=[...list].sort((a,b)=>(b.is_sponsored?1:0)-(a.is_sponsored?1:0)||(b.rating||0)-(a.rating||0)||(a.name||"").localeCompare(b.name||"","sv"));return list}
function distLabel(p){if(!me||!p.lat)return"";const d=km(me.lat,me.lon,p.lat,p.lon);return d<10?d.toFixed(1)+" km":Math.round(d)+" km"}
function cardHtml(p,full){const my=rates()[p.id]||0;const m=menuOf(p.id);const d=distLabel(p);const tel=safeTel(p.phone);const web=safeHttp(p.menu_url);const idj=JSON.stringify(String(p.id));const namej=JSON.stringify(String(p.name||""));const cityj=JSON.stringify(String(p.city||""));const phonej=JSON.stringify(String(p.phone||""));return `<article class="card"><button class="heart" onclick='toggleFav(${idj})'>${isFav(p.id)?"❤️":"🤍"}</button><button class="namebtn" onclick='openDetail(${idj})'><h2>${esc(p.name)}</h2></button><div class="meta"><span>${esc(p.city||"")}</span>${d?"<span>"+esc(d)+"</span>":""}${web?"<span class='badge'>Sajt</span>":""}${tel?"<span class='badge'>Tel</span>":""}${m.length?"<span class='badge'>Meny</span>":""}${p.is_sponsored?"<span class='badge s'>Sponsrad</span>":""}</div>${full?`<div class="stars">${[1,2,3,4,5].map(n=>`<span onclick='setRate(${idj},${n})'>${n<=my?"★":"☆"}</span>`).join("")}</div>`:""}${full&&p.description?`<p class="desc">${esc(p.description)}</p>`:""}<div class="row">${tel?`<a class="ring" href="tel:${esc(tel)}">📞 Ring</a>`:""}${p.lat&&p.lon?`<a class="map" target="_blank" rel="noopener noreferrer" href="https://maps.apple.com/?daddr=${encodeURIComponent(p.lat)},${encodeURIComponent(p.lon)}">📍 Karta</a>`:""}${web?`<a class="meny" target="_blank" rel="noopener noreferrer" href="${esc(web)}">🔗 Sajt</a>`:""}<button class="act claim" onclick='openClaim(${idj},${namej},${phonej})'>Äg</button></div>${full?`<button class="act claim" style="width:100%;margin-top:8px" onclick='openTip("syns_hogre",${idj},${namej},${cityj})'>Syns högre · 299 kr/mån</button><button class="act claim" style="width:100%;margin-top:8px" onclick='shareP(${namej},${cityj})'>Dela</button>`:""}${full&&m.length?`<p class="desc" style="margin-top:14px"><b>Digital meny</b></p>`+m.map(i=>`<div class="item"><span>${esc(i.name)}</span><span>${i.price_sek?esc(i.price_sek)+" kr":""}</span></div>`).join("")+`<button class="act claim" style="width:100%;margin-top:10px" onclick='slumpPizza(${idj})'>🎲 Slumpa pizza här</button>`:full?`<p class="desc">Ingen digital meny inlagd än.</p>`:""}</article>`}
function shareP(name,cty){const t="Ikväll: "+String(name||"")+(cty?" i "+cty:"")+" — Pizza Meny";if(navigator.share)navigator.share({title:t,text:t,url:SITE});else{navigator.clipboard.writeText(SITE+" — "+t);alert("Länk kopierad")}}
function render(){const list=getList();const cap=(city||document.getElementById("q").value.trim()||filter==="fav"||filter==="near")?800:80;document.getElementById("count").innerHTML=(!city&&filter==="all"?"Skriv en stad. Eller tryck Slumpa. ":"")+"<b style='color:#fff'>"+Math.min(list.length,cap)+"</b> pizzerior";document.getElementById("list").innerHTML=list.length?list.slice(0,cap).map(p=>cardHtml(p,false)).join(""):"<div class='empty'>"+(filter==="fav"?"Inga favoriter än. Tryck hjärtat på en pizzeria.":"Inget här. Tryck Saknas?")+"</div>"}
function openDetail(id){const p=all.find(x=>x.id===id);if(!p)return;document.getElementById("listPage").classList.remove("on");document.getElementById("detailPage").classList.add("on");document.getElementById("back").style.display="block";document.getElementById("ownerbar").style.display="none";document.getElementById("htitle").textContent=p.name;document.getElementById("sub").textContent=p.city||"";document.getElementById("detail").innerHTML=cardHtml(p,true)}
function goList(){document.getElementById("detailPage").classList.remove("on");document.getElementById("listPage").classList.add("on");document.getElementById("back").style.display="none";document.getElementById("ownerbar").style.display="flex";document.getElementById("htitle").textContent="🍕 Pizza Meny";document.getElementById("sub").textContent=all.length+" pizzerior · live";render()}
function openSlump(){document.getElementById("slumpMask").classList.add("on")}
function openHelp(){document.getElementById("helptitle").textContent="Pizza Meny";document.getElementById("helpApp").style.display="block";document.getElementById("helpOwner").style.display="none";document.getElementById("helpMask").classList.add("on")}
function openOwner(){document.getElementById("helptitle").textContent="Äg din sida";document.getElementById("helpApp").style.display="none";document.getElementById("helpOwner").style.display="block";document.getElementById("helpMask").classList.add("on")}
function pickPool(mode){let pool=all;if(mode==="city")pool=getList();if(mode==="fav")pool=all.filter(p=>isFav(p.id));return pool}
function doSlump(mode){document.getElementById("slumpMask").classList.remove("on");if(mode==="city"&&!city){alert("Välj en stad först.");return}const pool=pickPool(mode);if(!pool.length){alert("Inget att slumpa där.");return}ovenP=pool[Math.floor(Math.random()*pool.length)];ovenPlay()}
function slumpPizza(id){const m=menuOf(id);if(!m.length){alert("Ingen digital meny på den här pizzerian än.");return}const x=m[Math.floor(Math.random()*m.length)];alert("🍕 "+x.name+(x.price_sek?" · "+x.price_sek+" kr":""))}
function ovenStart(){document.getElementById("slumpMask").classList.remove("on");const pool=getList().length?getList():all;if(!pool.length){alert("Inget att slumpa");return}ovenP=pool[Math.floor(Math.random()*pool.length)];ovenPlay()}
function ovenPlay(){const door=document.getElementById("door");const pie=document.getElementById("ovenPizza");const tur=document.getElementById("turtle");const fly=document.getElementById("flypie");document.getElementById("ovenActs").style.display="none";document.getElementById("ovenTitle").textContent="Sköldpaddan kommer";document.getElementById("ovenSub").textContent="Pizza in i ugnen";pie.classList.remove("show");tur.classList.remove("in","go","toss","walk","done");fly.classList.remove("go");door.classList.remove("shut");document.getElementById("oven").classList.add("on");requestAnimationFrame(()=>{tur.classList.add("in","walk")});setTimeout(()=>{tur.classList.remove("walk");tur.classList.add("toss");fly.classList.add("go");setTimeout(()=>{door.classList.add("shut")},180);setTimeout(()=>{pie.classList.add("show");tur.classList.add("done");setTimeout(()=>{door.classList.remove("shut");document.getElementById("ovenTitle").textContent=ovenP.name;const pizza=menuOf(ovenP.id);document.getElementById("ovenSub").textContent=pizza.length?("🍕 "+pizza[Math.floor(Math.random()*pizza.length)].name):(ovenP.city||"");document.getElementById("ovenActs").style.display="block";const ring=document.getElementById("ovenRing");const tel=safeTel(ovenP.phone);if(tel){ring.style.display="block";ring.onclick=()=>{location.href="tel:"+tel};ring.textContent="📞 Ring"}else ring.style.display="none"},480)},900)},900)}
function ovenAgain(){document.getElementById("oven").classList.remove("on");document.getElementById("ovenPizza").classList.remove("show");document.getElementById("turtle").classList.remove("in","go","toss","walk","done");document.getElementById("flypie").classList.remove("go");setTimeout(ovenStart,80)}
function ovenOpen(){document.getElementById("oven").classList.remove("on");if(ovenP)openDetail(ovenP.id)}
function digits(s){s=(s||"").replace(/\D/g,"");if(s.startsWith("46")&&s.length>=10)s="0"+s.slice(2);return s}
function openClaim(id,name,listed){document.getElementById("pid").value=id;document.getElementById("pid").dataset.listed=listed||"";document.getElementById("stitle").textContent="Äg "+name;document.getElementById("sdesc").textContent=listed?"Samma nummer som på kortet.":"Pizzerians nummer. Villkor skickas om ni sen tecknar Syns högre.";document.getElementById("cname").value="";document.getElementById("cphone").value=listed||"";document.getElementById("cmail").value="";const web=document.getElementById("cweb");if(web)web.value="";const boost=document.getElementById("cboost");if(boost)boost.checked=false;const hp=document.getElementById("chp");if(hp)hp.value="";formOpen=Date.now();document.getElementById("mask").classList.add("on")}
function closeSheet(){document.getElementById("mask").classList.remove("on")}
async function sendClaim(){if(document.getElementById("chp")&&document.getElementById("chp").value)return;if(Date.now()-formOpen<1200){alert("Vänta en sekund och skicka igen.");return}if(tooSoon("pm_claim",20000)){alert("Vänta lite mellan claim.");return}const name=document.getElementById("cname").value.trim().slice(0,80),phone=document.getElementById("cphone").value.trim().slice(0,30);const email=document.getElementById("cmail").value.trim().slice(0,120);const webEl=document.getElementById("cweb");const web=webEl?webEl.value.trim().slice(0,200):"";const boost=!!(document.getElementById("cboost")&&document.getElementById("cboost").checked);const pid=document.getElementById("pid").value,listed=document.getElementById("pid").dataset.listed||"";if(!uuidOk(pid)||!name||!phone){alert("Namn och telefon");return}if(listed&&digits(listed)&&digits(phone)!==digits(listed)){alert("Numret måste matcha: "+listed);return}const pend=await fetch(SB+"/rest/v1/claims?select=id&pizzeria_id=eq."+encodeURIComponent(pid)+"&status=eq.pending",{headers:{apikey:KEY,Authorization:"Bearer "+KEY}});if(pend.ok&&(await pend.json()).length){alert("Redan en claim.");return}const r=await fetch(SB+"/rest/v1/claims",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({pizzeria_id:pid,status:"pending",verification_method:boost?"syns_hogre":"phone",verification_data:JSON.stringify({name,phone,email,web,boost,price:boost?"299":null})})});if(!r.ok){alert("Kunde inte skicka.");return}closeSheet();alert(boost?"Tack. Vi hör av oss om Syns högre.":"Tack. Vi granskar.")}
function openTip(kind,pid,name,cty){document.getElementById("tipkind").value=kind==="syns_hogre"?"syns_hogre":"saknas";document.getElementById("tippid").value=pid||"";document.getElementById("tname").value=name||"";document.getElementById("tcity").value=cty||city||document.getElementById("q").value||"";document.getElementById("tphone").value="";document.getElementById("tweb").value="";document.getElementById("tnote").value=kind==="syns_hogre"?"Vill synas högre":"";const hp=document.getElementById("thp");if(hp)hp.value="";document.getElementById("tiptitle").textContent=kind==="syns_hogre"?"Vill synas högre":"Saknas en pizzeria?";document.getElementById("tipdesc").textContent=kind==="syns_hogre"?"Intresse. Villkor kommer först när ni tecknar.":"Efterkontroll mot egen sajt eller nummer.";formOpen=Date.now();document.getElementById("tipMask").classList.add("on")}
async function sendTip(){if(document.getElementById("thp")&&document.getElementById("thp").value)return;if(Date.now()-formOpen<1200){alert("Vänta en sekund och skicka igen.");return}if(tooSoon("pm_tip",15000)){alert("Vänta lite mellan tips.");return}const kind=document.getElementById("tipkind").value==="syns_hogre"?"syns_hogre":"saknas";const pid=document.getElementById("tippid").value||null;const body={kind,pizzeria_id:pid&&uuidOk(pid)?pid:null,name:document.getElementById("tname").value.trim().slice(0,80),city:document.getElementById("tcity").value.trim().slice(0,60),phone:document.getElementById("tphone").value.trim().slice(0,30)||null,website:document.getElementById("tweb").value.trim().slice(0,200)||null,note:document.getElementById("tnote").value.trim().slice(0,500)||null};if(!body.name||!body.city){alert("Namn och stad");return}const r=await fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok){alert("Kunde inte skicka.");return}document.getElementById("tipMask").classList.remove("on");alert("Tack. Inskickat.")}
function openContact(){document.getElementById("helpMask").classList.remove("on");document.getElementById("meMask").classList.remove("on");formOpen=Date.now();document.getElementById("kname").value="";document.getElementById("kmail").value="";document.getElementById("kmsg").value="";document.getElementById("hp").value="";document.getElementById("contactMask").classList.add("on")}
async function sendContact(){if(document.getElementById("hp").value)return;if(Date.now()-formOpen<2500){alert("Vänta en sekund och skicka igen.");return}if(tooSoon("pm_mail",60000)){alert("Vänta en minut mellan meddelanden.");return}const name=document.getElementById("kname").value.trim().slice(0,80);const mail=document.getElementById("kmail").value.trim().slice(0,120);const msg=document.getElementById("kmsg").value.trim().slice(0,800);if(!name||!mail||!msg){alert("Namn, e-post och meddelande");return}if(!emailOk(mail)||msg.length<8){alert("Kolla e-post och skriv lite mer.");return}let body={kind:"kontakt",name,city:"Kontakt",phone:null,website:mail,note:msg};let r=await fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(body)});if(!r.ok){body.kind="saknas";body.note="KONTAKT "+mail+" | "+msg;r=await fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(body)})}if(!r.ok){alert("Kunde inte skicka.");return}document.getElementById("contactMask").classList.remove("on");alert("Tack. Vi läser det.")}
load();
