const SB="https://cmmnqckszwgsvaaawouw.supabase.co";
const KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtbW5xY2tzendnc3ZhYWF3b3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc1MDM3OTcsImV4cCI6MjEwMzA3OTc5N30.3q6gLw1Zz2ql__Va29fYPwjCkdnJ9-cO1MmKmluF30g";
const TOP=["Stockholm","Göteborg","Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Norrköping","Jönköping","Lund","Umeå","Eskilstuna"];
const LEAK=["København","Kobenhavn","Copenhagen","Oslo","Helsinki","Vaasa"];
const COLS="id,name,city,country,phone,lat,lon,menu_url,description,rating,is_sponsored";
const CACHE_KEY="pm_cache_v2";
const SITE="https://pizza-meny.vercel.app";
let all=[], items=[], filter="all", sort="rank", city="", me=null, ovenP=null, formOpen=0, typeT=0;
function esc(s){return String(s==null?"":s).replace(/[&<>"']/g,c=>"&#"+c.charCodeAt(0)+";")}
function emailOk(s){return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(String(s||"").trim())}
function safeHttp(u){u=String(u||"").trim();if(/^https?:\/\//i.test(u)&&u.indexOf(" ")<0&&u.indexOf("<")<0)return u;return""}
function safeTel(p){const d=String(p||"").replace(/[^\d+]/g,"");return d.length>=7?d:""}
function uuidOk(id){return /^[0-9a-f-]{8,36}$/i.test(String(id||""))}
function tooSoon(key,ms){const last=+localStorage.getItem(key)||0;if(Date.now()-last<ms)return true;localStorage.setItem(key,String(Date.now()));return false}
function favs(){try{const a=JSON.parse(localStorage.getItem("pm_fav")||"[]");return Array.isArray(a)?a.filter(uuidOk):[]}catch(e){return[]}}
function saveFav(a){localStorage.setItem("pm_fav",JSON.stringify(a.filter(uuidOk).slice(0,400)))}
function isFav(id){return favs().includes(id)}
function toggleFav(id){if(!uuidOk(id))return;const a=favs();const i=a.indexOf(id);if(i>=0)a.splice(i,1);else a.push(id);saveFav(a);render();if(document.getElementById("detailPage").classList.contains("on"))openDetail(id)}
function taggOk(s){return /^[a-z0-9_]{3,20}$/.test(String(s||""))}
function normTagg(s){return String(s||"").trim().toLowerCase().replace(/\s+/g,"_").replace(/[^a-z0-9_]/g,"").slice(0,20)}
function profile(){try{const p=JSON.parse(localStorage.getItem("pm_me")||"{}");return p&&typeof p==="object"?p:{}}catch(e){return{}}}
function saveProfile(p){const clean={id:String(p.id||"").slice(0,40),name:normTagg(p.name||""),email:String(p.email||"").slice(0,120),verified:!!p.verified,verify:p.verified?"":String(p.verify||"").slice(0,64)};localStorage.setItem("pm_me",JSON.stringify(clean))}
function friends(){try{const f=JSON.parse(localStorage.getItem("pm_friends")||"{}");return {in:Array.isArray(f.in)?f.in:[],out:Array.isArray(f.out)?f.out:[],ok:Array.isArray(f.ok)?f.ok:[]}}catch(e){return{in:[],out:[],ok:[]}}}
function saveFriends(f){localStorage.setItem("pm_friends",JSON.stringify({in:(f.in||[]).slice(0,80),out:(f.out||[]).slice(0,80),ok:(f.ok||[]).slice(0,80)}))}
function eats(){try{const a=JSON.parse(localStorage.getItem("pm_eats")||"[]");return Array.isArray(a)?a.slice(0,40):[]}catch(e){return[]}}
function logEat(p){if(!p||!p.id)return;const a=eats().filter(x=>x.id!==p.id);a.unshift({id:p.id,name:String(p.name||"").slice(0,80),city:String(p.city||"").slice(0,40),t:Date.now()});localStorage.setItem("pm_eats",JSON.stringify(a.slice(0,40)))}
function newTok(){const a=new Uint8Array(16);if(crypto.getRandomValues)crypto.getRandomValues(a);return Array.from(a,b=>("0"+(b&255).toString(16)).slice(-2)).join("")}
function verifyUrl(){const p=profile();if(!p.verify)return"";return SITE+"/?verify="+encodeURIComponent(p.verify)}
function applyVerify(){let t="";try{t=new URLSearchParams(location.search).get("verify")||""}catch(e){t=""}if(!t||t.length<16)return;const p=profile();if(p.verify&&p.verify===t&&p.email){p.verified=true;p.verify="";saveProfile(p);try{history.replaceState({},"",location.pathname)}catch(e){}alert("E-post verifierad. Vänner kan synas.")}}
function loggedIn(){const p=profile();return !!(p.email&&p.name)}
function paintFriends(){const f=friends();const fin=document.getElementById("fin");const fout=document.getElementById("fout");const fok=document.getElementById("fok");const feats=document.getElementById("feats");if(!fin)return;fin.innerHTML=f.in.length?"<p style='margin-top:14px'><b>Att acceptera</b></p>"+f.in.map(x=>`<div class="frow"><div><b>@${esc(x.tagg)}</b><span>Vill bli vän</span></div><div><button class="fbtn ok" onclick='acceptFriend(${JSON.stringify(x.tagg)})'>Ja</button> <button class="fbtn" onclick='denyFriend(${JSON.stringify(x.tagg)})'>Nej</button></div></div>`).join(""):"";fout.innerHTML=f.out.length?"<p style='margin-top:14px'><b>Skickade</b></p>"+f.out.map(x=>`<div class="frow"><div><b>@${esc(x.tagg)}</b><span>Väntar</span></div><button class="fbtn" onclick='cancelFriend(${JSON.stringify(x.tagg)})'>Ta tillbaka</button></div>`).join(""):"";fok.innerHTML=f.ok.length?"<p style='margin-top:14px'><b>Era vänner</b></p>"+f.ok.map(x=>`<div class="frow"><div><b>@${esc(x.tagg)}</b><span>${x.last?esc(x.last.name)+(x.last.city?" · "+esc(x.last.city):""):"Inget valt än"}</span></div><button class="fbtn bad" onclick='dropFriend(${JSON.stringify(x.tagg)})'>Ta bort</button></div>`).join(""):"<p style='margin-top:12px'>Inga vänner än. Sök en tagg.</p>";const mine=eats();feats.innerHTML=mine.length?"<p style='margin-top:14px'><b>Du senast</b></p>"+mine.slice(0,5).map(x=>`<div class="frow"><div><b>${esc(x.name)}</b><span>${esc(x.city||"")}</span></div></div>`).join(""):""}
function paintMe(){const p=profile();const guest=document.getElementById("meGuest");const inn=document.getElementById("meIn");const vbox=document.getElementById("verifyBox");const hint=document.getElementById("mehint");const inOk=loggedIn();if(guest)guest.style.display=inOk&&p.verified?"none":"block";if(inn)inn.style.display=inOk&&p.verified?"block":"none";if(vbox)vbox.style.display=(!p.verified&&p.email&&p.verify)?"block":"none";if(hint){if(p.verified)hint.textContent="Inloggad som @"+(p.name||"")+".";else if(p.email)hint.textContent="Konto skapat. Verifiera e-post innan vänner syns.";else hint.textContent="Välj en tagg. E-post krävs."}const box=document.getElementById("mebox");if(box&&p.verified)box.innerHTML="<b>@"+esc(p.name||"")+"</b><br><span style='color:var(--muted)'>"+esc(p.email||"")+" · verifierad</span>";const rt=document.getElementById("retag");if(rt&&p.name)rt.value=p.name;if(inOk&&p.verified)paintFriends();cancelDel()}
function openMe(){const p=profile();const n=document.getElementById("mename");const e=document.getElementById("memail");if(n)n.value=p.name||"";if(e)e.value=p.email||"";paintMe();document.getElementById("meMask").classList.add("on")}
function saveMe(){const name=normTagg(document.getElementById("mename").value);const email=document.getElementById("memail").value.trim().toLowerCase().slice(0,120);if(!taggOk(name)){alert("Tagg: 3–20 tecken. Bokstäver, siffror, _");return}if(!emailOk(email)){alert("E-post krävs för att öppna konto");return}const p=profile();if(p.email!==email){p.verified=false;p.verify=newTok()}if(!p.verify&&!p.verified)p.verify=newTok();p.name=name;p.email=email;if(!p.id)p.id="u"+Date.now();saveProfile(p);paintMe();if(!tooSoon("pm_konto",60000)){fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({kind:"konto",name,city:"Konto",phone:null,website:email,note:"verify_pending"})}).catch(()=>{})}if(p.verified)paintMe();else alert("Konto skapat. Kopiera verifieringslänken och öppna den på den här telefonen.")}
function copyVerify(){const u=verifyUrl();if(!u){alert("Skapa konto först");return}if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(u).then(()=>alert("Länk kopierad. Öppna den här.")).catch(()=>{location.href=u})}else location.href=u}
function changeTagg(){const p=profile();if(!p.verified)return;const name=normTagg(document.getElementById("retag").value);if(!taggOk(name)){alert("Tagg: 3–20 tecken. Bokstäver, siffror, _");return}p.name=name;saveProfile(p);paintMe();alert("Tagg sparad: @"+name)}
function sendFriend(){const p=profile();if(!p.verified){alert("Verifiera e-post först");return}const tagg=normTagg(document.getElementById("fsearch").value);if(!taggOk(tagg)){alert("Skriv en tagg");return}if(tagg===p.name){alert("Det är du");return}const f=friends();if(f.ok.some(x=>x.tagg===tagg)){alert("Redan vän");return}if(f.out.some(x=>x.tagg===tagg)){alert("Redan skickad");return}const hit=f.in.find(x=>x.tagg===tagg);if(hit){acceptFriend(tagg);return}f.out.unshift({tagg,t:Date.now()});saveFriends(f);document.getElementById("fsearch").value="";paintFriends();if(!tooSoon("pm_van",8000)){fetch(SB+"/rest/v1/tips",{method:"POST",headers:{apikey:KEY,Authorization:"Bearer "+KEY,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({kind:"van",name:p.name,city:tagg,phone:null,website:p.email||null,note:"friend_request"})}).catch(()=>{})}}
function acceptFriend(tagg){tagg=normTagg(tagg);const f=friends();if(!f.ok.some(x=>x.tagg===tagg))f.ok.unshift({tagg,t:Date.now(),last:null});f.in=f.in.filter(x=>x.tagg!==tagg);f.out=f.out.filter(x=>x.tagg!==tagg);saveFriends(f);paintFriends()}
function denyFriend(tagg){tagg=normTagg(tagg);const f=friends();f.in=f.in.filter(x=>x.tagg!==tagg);saveFriends(f);paintFriends()}
function cancelFriend(tagg){tagg=normTagg(tagg);const f=friends();f.out=f.out.filter(x=>x.tagg!==tagg);saveFriends(f);paintFriends()}
function dropFriend(tagg){tagg=normTagg(tagg);if(!confirm("Ta bort @"+tagg+" som vän?"))return;const f=friends();f.ok=f.ok.filter(x=>x.tagg!==tagg);saveFriends(f);paintFriends()}
function askDel(){document.getElementById("del1").style.display="none";document.getElementById("del2").style.display="block";const i=document.getElementById("delconfirm");if(i){i.value="";i.focus()}}
function cancelDel(){const a=document.getElementById("del1");const b=document.getElementById("del2");if(a)a.style.display="block";if(b)b.style.display="none"}
function doDel(){const p=profile();const v=normTagg(document.getElementById("delconfirm").value);if(!p.name||v!==p.name){alert("Skriv din tagg exakt");return}localStorage.removeItem("pm_me");localStorage.removeItem("pm_friends");localStorage.removeItem("pm_eats");document.getElementById("meMask").classList.remove("on");alert("Kontot är borta på den här telefonen.")}
function ovenDismiss(){document.getElementById("oven").classList.remove("on");document.getElementById("ovenPizza").classList.remove("show");const tur=document.getElementById("turtle");if(tur)tur.classList.remove("in","go","toss","walk","done");const fly=document.getElementById("flypie");if(fly)fly.classList.remove("go");ovenP=null}
